[versions]

java = "17"

# plugins
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.3.10"
# https://github.com/Kotlin/dokka/releases
dokka = "2.1.0"
# https://github.com/Kotlin/kotlinx-kover/releases
kover = "0.9.7"
# https://github.com/melix/jmh-gradle-plugin/tags (for benchmarks)
jmhPlugin = "0.7.3"
# https://github.com/GradleUp/shadow/releases (for benchmarks)
shadow = "9.3.1"
# https://github.com/researchgate/gradle-release/releases
release = "3.1.0"

# main
# https://github.com/jayo-projects/jayo/tags
jayo = "0.1.0-beta8"
# https://github.com/jspecify/jspecify/releases
jspecify = "1.0.0"

# third party
# https://mvnrepository.com/artifact/org.brotli/dec
brotli = "0.1.2"
# https://github.com/Kotlin/kotlinx.coroutines/releases
coroutines = "1.10.2"

# tests and samples
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = "3.27.7"
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junit = "6.0.2"
# https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer
junitPioneer = "2.3.0"
# https://mvnrepository.com/artifact/io.mockk/mockk
mockk = "1.14.9"
# https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
okhttp = "5.3.2"
# https://mvnrepository.com/artifact/org.slf4j/slf4j-jdk-platform-logging
slf4j = "2.0.17"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logback = "1.5.29"
# https://mvnrepository.com/artifact/org.hamcrest/hamcrest
hamcrest = "3.0"
# https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5
httpClient5 = "5.6"
# https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-client
jetty = "12.1.6"
# https://mvnrepository.com/artifact/org.asynchttpclient/async-http-client
asyncHttpClient = "3.0.7"
# https://mvnrepository.com/artifact/org.jsoup/jsoup
jsoup = "1.22.1"

# benchmarks
# https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-core
jmh = "1.37"

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
kover-gradle-plugin = { group = "org.jetbrains.kotlinx", name = "kover-gradle-plugin", version.ref = "kover" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
release = { id = "net.researchgate.release", version.ref = "release" }
